### ISSUE TITLE
[P3B-3] Shopping list information

### ISSUE THREAD

**Issue by allenpoon** [ierg4210/shop52#2]
Your shopping list is store on localStorage with following data:
{id, name, quantity, price, subtotal}

By requirement, it should 
 - store {id, quantity}
 - request {name, price} from AJAX
 - calculate and display the total amount (your total is based on subtotal and subtotal is read from localStorage), subtotal can be calculated by price and quantity

**Comment by s1155035142** [comment]
The 'name', 'price' and 'subtotal' will be updated from production information when changing quantity of cart item. The production information is requested from AJAX and the additional data in localstorage is only for displaying shopping cart. I have pushed a new commit 62246b60c70d1ca39b48c46778b69289b6949cd5. Now it will additionally update the localstorage on page reload.

**Comment by diaowenrui** [comment]
[TA comment] After checking source codes shown by the shop owner, the price is got from DB. Not an issue.

**Comment by allenpoon** [comment]
you mean my issue is not an issue?

**Comment by diaowenrui** [comment]
[TA comment] It only affects the local shopping cart UI. It doesn't affect the checkout part.

**Comment by allenpoon** [comment]
I finally found the SQL request in code. Thanks!
